version: "3.3"

services:
  db:
    image: postgres
    container_name: db
    restart: always
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env
    networks:
      - backend
  whatsapp:
    image: whatsapp
    container_name: whatsapp
    user: node
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    ports:
      - 3010:3010
    volumes:
      - ./:/app
    networks:
      - backend
    # command: npm run dev
    command: npm run start
networks:
  backend:
volumes:
  database: