version: "3.3"

services:
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: cupsadmin
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "3306:3306"
  whatsapp:
    image: whatsapp
    container_name: whatsapp
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    ports:
      - 3010:3010
    volumes:
      - ./:/app
volumes:
  mysql: