version: "3.3"

services:
  whatsapp:
    image: whatsapp
    container_name: whatsapp
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    ports:
      - 3010:3010
    volumes:
      - ./:/app
volumes:
  database: