version: "3.3"

services:
  db:
    image: postgres
    container_name: db
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  whatsapp:
    image: whatsapp
    container_name: whatsapp
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    ports:
      - 3010:3010
    volumes:
      - ./:/app
volumes:
  data: