version: "3.3"

services:
  whatsapp:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    image: whatsapp
    container_name: whatsapp
    ports:
      - 3010:3010
    volumes:
      - ./:/app