version: "3.3"

services:
  whatsapp:
    image: whatsapp
    container_name: whatsapp
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3010:3010
      - 5000:5432
    volumes:
      - ./:/app
volumes:
  database: