version: "3.3"

services:
  db:
    image: postgres
    container_name: db
    restart: always
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env.database
    networks:
      - backend
  whatsapp:
    image: whatsapp
    container_name: whatsapp
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    links: 
      - db:database
    ports:
      - 3010:3010
    volumes:
      - ./:/app
    networks:
      - backend
networks:
  backend:
    name: backend
    driver: backend
volumes:
  database: